name: Code Style

on: 
  push:
    branches: [main, develop] 
  pull_request:
    branches: [main]

jobs:
  uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        
      - name: Run Ruff check
        run: uv run ruff check
        
      - name: Run Ruff format
        run: uv run ruff format
        
      - name: RUN Mypy
        run: uv run mypy src
        
      - name: Run Pytest
        run: uv run pytest -n auto
        
